#@endpoint = http://localhost:8080
@endpoint = https://protoapp.kube.benco.io

### Get an order
GET {{endpoint}}/api/orders/b902dee0-013f-48ac-8ddb-28226e26e0d3

### Get all orders!
GET {{endpoint}}/api/orders


### Create an order
POST {{endpoint}}/api/orders
Content-Type: application/json

{
  "product": "Lemon Curd",
  "description": "An order for some delicious lemon curd",
  "items": {{$randomInt 1 200}}
}

### Delete an order
DELETE {{endpoint}}/api/orders/2f75ca1a-4aa5-4b0c-8ce5-f29662843962
