#@endpoint = http://localhost:8080
@endpoint = https://protoapp.kube.benco.io

### Create an order
# @name createOrder
POST {{endpoint}}/api/orders/
Content-Type: application/json

{
  "product": "Lemon Curd",
  "description": "An order for some delicious lemon curd",
  "items": {{$randomInt 1 200}}
}

@orderId = {{createOrder.response.body.id}}
#@orderId = wewewew

### Get an order
GET {{endpoint}}//api/orders/{{orderId}}

### Delete an order
DELETE {{endpoint}}/api/orders/{{orderId}}

### Get all orders!
GET {{endpoint}}/api/orders

### Health check
GET {{endpoint}}/healthz

### Health check
GET {{endpoint}}/metrics