{
 "title": "Application Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "API: Orders get/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(order_get_total[2m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API: Orders create/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(order_create_total[2m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API: Orders delete/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(order_delete_total[2m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go: Allocated Mem",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{app_kubernetes_io_name=\"cassandra-go-api\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Go: Theads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{app_kubernetes_io_name=\"cassandra-go-api\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}