default:
  image: ghcr.io/benc-uk/golang-docker:latest

  before_script:
    - go get -u golang.org/x/lint/golint
    - go get gotest.tools/gotestsum

stages:
  - test
  - build
  - post-build
  - deploy

code-check:
  stage: test
  script: make format lint

test:
  stage: test
  script: make test

build-image:
  stage: build
  script:
    - make build

push-image:
  only:
    refs:
      - main
  needs:
    - build-image
  stage: post-build
  script:
    - make push
