# This file is a template, and might need editing before it works on your project.
# Read more about the feature here: https://docs.gitlab.com/ee/user/project/merge_requests/accessibility_testing.html

default:
  image: golang:1.15.6-buster

  before_script:
    - go get -u golang.org/x/lint/golint
    - go get gotest.tools/gotestsum

stages:
  - test
  - build
  - post-build
  - deploy

code-check:
  stage: test
  script: make format lint

test:
  stage: test
  script: make test

build-image:
  stage: build
  script: make build

push-image:
  needs:
    - build-image
  stage: post-build
  script:
    - make push
