#@endpoint = http://localhost:8080
@endpoint = https://testapp.kube.benco.io

###
GET {{endpoint}}/fruits

###
POST {{endpoint}}/fruits
Content-Type: application/json

{
  "name": "Apple {{$randomInt 0 10000}}",
  "description": "Round and green"
}