@endpoint = http://localhost:8080
#@endpoint = https://testapp.kube.benco.io
@name = Apple 2833333

###
GET {{endpoint}}/fruits

###
POST {{endpoint}}/fruits
Content-Type: application/json

{
  "name": "{{name}}",
  "description": "Round and green"
}

###
GET {{endpoint}}/fruits/{{name}}

###
DELETE {{endpoint}}/fruits/{{name}}
