apiVersion: v1
kind: Secret
metadata:
  name: {{ include "testapp.fullname" . }}-grafana-datasources
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://{{ .Release.Name }}-prometheus-server
      - name: InfluxDB
        type: influxdb
        url: http://influx-influxdb:8086
        database: k6_results
