replicas: 2
ingress:
  enabled: true
  hosts:
    - host: protoapp.kube.benco.io
      paths: ["/"]
  tls:
    - secretName: kube-benco-io-cert
      hosts:
        - protoapp.kube.benco.io

cassandra:
  replicaCount: 1
  persistence:
    enabled: false
