apiVersion: v2
name: prom-grafana
description: A wrapper chart for deploying Prometheus & Grafana
type: application

version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 12.0.1

  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 6.1.12
