name: CI & Build

on:
  push:
  pull_request:
    branches: [main]

env:
  DOCKER_REG: ghcr.io
  DOCKER_REPO: benc-uk/cassandra-prototype

jobs:
  check:
    name: "Run tests and checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Set Go version and paths"
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.0"

      - name: "Install extra test & build tools"
        run: |
          go get -u golang.org/x/lint/golint
          go get gotest.tools/gotestsum

      - name: "Check code"
        run: make lint format

      - name: "Run all unit tests"
        run: make test-output

      - name: "Generate test & code coverage reports"
        if: success() || failure()
        run: make reports

  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: check
    name: "Build container image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Create datestamp image tag" # Nicer than using github runid, I think
        run: echo "DOCKER_TAG=$(date +%d-%m-%Y.%H%M)" >> $GITHUB_ENV

      - name: "Build Image"
        run: docker build -f Dockerfile -t $DOCKER_REG/$DOCKER_REPO:$DOCKER_TAG .

      - name: "Login to GitHub container registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: "Push Image"
        run: docker push  $DOCKER_REG/$DOCKER_REPO

      - name: Trigger deployment with workflows_dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy to AKS
          token: ${{ secrets.DEPLOYMENT_PAT }}
          inputs: '{ "imageTag": "${{ env.DOCKER_TAG }}" }'
