name: Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      imageTag:
        required: true
        default: latest
        description: Tag image to be deployed

env:
  DOCKER_REG: ghcr.io
  DOCKER_REPO: benc-uk/cassandra-prototype
  AKS_NAME: benc
  AKS_RESGRP: aks
  RELEASE_NAME: app
  DOMAIN_SUFFIX: kube.benco.io

jobs:
  deploy-test:
    name: Deploy to Test
    env:
      NAMESPACE: proto-test
    environment:
      name: "AKS: test"
      url: "https://${{ env.NAMESPACE }}.${{ env.DOMAIN_SUFFIX }}/"

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v1

      - name: "Connect to AKS"
        uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          resource-group: "${{ env.AKS_RESGRP }}"
          cluster-name: "${{ env.AKS_NAME }}"
        id: login

      - name: "Helm dep update"
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm dep update kubernetes/helm/cassandra-go-api

      - name: "Helm install into ${{ env.NAMESPACE }}"
        run: |
          helm upgrade --install $RELEASE_NAME \
          kubernetes/helm/cassandra-go-api \
          --namespace $NAMESPACE \
          --values kubernetes/helm/app-values.yaml \
          --set "image.reg=${{ env.DOCKER_REG }},image.repo=${{ env.DOCKER_REPO }},image.tag=${{ github.event.inputs.imageTag }},ingress.hosts[0].host=$NAMESPACE.$DOMAIN_SUFFIX,ingress.tls[0].hosts[0]=$NAMESPACE.$DOMAIN_SUFFIX"

  api-test:
    name: Run API Test
    needs: deploy-test
    env:
      NAMESPACE: proto-test

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v1

      - name: "Wait for deployment to be ready"
        run: .github/url-check.sh -u "https://${{ env.NAMESPACE }}.${{ env.DOMAIN_SUFFIX }}"

      # Run the tests inside a container with Newman
      - name: "Run API tests with Postman/newman"
        uses: docker://dannydainton/htmlextra
        with:
          args: run /github/workspace/testing/api/postman.json -n 5 --global-var API_ENDPOINT="https://${{ env.NAMESPACE }}.${{ env.DOMAIN_SUFFIX }}" -r htmlextra --reporter-htmlextra-export /github/workspace/testing/api/api-report.html

      - name: "Upload API test results"
        uses: actions/upload-artifact@v2
        with:
          name: api-test-result
          path: testing/api/api-report.html

  load-test:
    name: Run Load Test
    needs: deploy-test
    env:
      NAMESPACE: proto-test

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v1

      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Wait for deployment to be ready"
        run: .github/url-check.sh -u "https://${{ env.NAMESPACE }}.${{ env.DOMAIN_SUFFIX }}"

      - name: "Run K6 load tests using ACI"
        run: ./run-azure.sh "https://${{ env.NAMESPACE }}.${{ env.DOMAIN_SUFFIX }}" 5
        working-directory: testing/load

      - name: "Convert results to HTML"
        run: |
          wget https://github.com/benc-uk/k6-reporter/releases/download/1.1.0/k6-reporter
          chmod +x ./k6-reporter
          ./k6-reporter ./load-test-result.json ./load-test-result.html
        working-directory: testing/load

      - name: "Upload load test results"
        uses: actions/upload-artifact@v2
        with:
          name: load-test-result
          path: testing/load/load-test-result.html

  deploy-staging:
    name: Deploy to Staging
    needs: api-test
    env:
      NAMESPACE: proto-staging
    environment:
      name: "AKS: staging"
      url: "https://${{ env.NAMESPACE }}.${{ env.DOMAIN_SUFFIX }}/"

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v1

      - name: "Connect to AKS"
        uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          resource-group: "${{ env.AKS_RESGRP }}"
          cluster-name: "${{ env.AKS_NAME }}"
        id: login

      - name: "Helm dep update"
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm dep update kubernetes/helm/cassandra-go-api

      - name: "Helm install into ${{ env.NAMESPACE }}"
        run: |
          helm upgrade --install $RELEASE_NAME \
          kubernetes/helm/cassandra-go-api \
          --namespace $NAMESPACE \
          --values kubernetes/helm/app-values.yaml \
          --set "image.reg=${{ env.DOCKER_REG }},image.repo=${{ env.DOCKER_REPO }},image.tag=${{ github.event.inputs.imageTag }},ingress.hosts[0].host=$NAMESPACE.$DOMAIN_SUFFIX,ingress.tls[0].hosts[0]=$NAMESPACE.$DOMAIN_SUFFIX"
